config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  resources :export do
    collection do
      get :export_file
    end
  end

  resources :users_manage

  devise_for :users, :controllers => {registrations: 'registrations'}

  resources :show_map do
    collection do
      get :delete_map_order
    end
  end
    

  resources :items do
    collection do
      get :insert
      get :suppliers
      get :input
      get :add_information
    end
  end

 resources :map_order do
  collection do
    post :creates
  end
 end

  resources :inventory_items
  resources :purchase_orders do
    collection do 
      get :get_data
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    user ||= User.new

    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :moderator
      can :manage, User, user_id: user.id
      can :create, User
      can :manage, :map_order
      can :manage, :show_map
      can :manage, :item
      can :manage, :inventory_item
      can :manage, :purchase_order
      # can :read, :all
    else
       # Guest user aka. anonymous
      # can :read, :all
    end
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/account_object.rb
class AccountObject < ActiveRecord::Base
  establish_connection DB_CONF
  self.table_name = 'AccountObject'
  has_many :item, foreign_key: :supplier_id
  has_one :account_object, primary_key: :AccountObjectID
end

app/models/container_type.rb
class ContainerType < ActiveRecord::Base
  acts_as_paranoid
end

app/models/high_score.rb
class HighScore < ActiveRecord::Base
end

app/models/inventory_item.rb
class InventoryItem < ActiveRecord::Base
  establish_connection DB_CONF
  self.table_name = 'InventoryItem'
  has_one :unit, foreign_key: :UnitID, primary_key: :UnitID
  has_many :item, foreign_key: :item_id, primary_key: :InventoryItemID
end

app/models/item.rb
class Item < ActiveRecord::Base
  acts_as_paranoid
  has_one :account_object , foreign_key: :AccountObjectID, primary_key: :supplier_id
end

app/models/map_item.rb
class MapItem < ActiveRecord::Base
  self.table_name = 'map_item'
  has_many :pu_order_detail ,foreign_key: :InventoryItemID, primary_key: :ItemID
  has_many :inventory_item, foreign_key: :InventoryItemID, primary_key: :ItemID
end

app/models/map_purchase.rb
class MapPurchase < ActiveRecord::Base
  has_many :purchase_order, foreign_key: :RefID, primary_key: :RefID
  has_many :map_item, foreign_key: :map_purchase_id

  validates_presence_of :map_id
end

app/models/pu_order_detail.rb
class PuOrderDetail < ActiveRecord::Base
  establish_connection DB_CONF
  self.table_name = 'PuOrderDetail'

  belongs_to :purchase_order, foreign_key: :RefID
  has_one :item , foreign_key: :item_id, primary_key: :InventoryItemID
  has_one :inventory_item,  foreign_key: :InventoryItemID, primary_key: :InventoryItemID
end

app/models/purchase_order.rb
class PurchaseOrder < ActiveRecord::Base
  establish_connection DB_CONF
  self.table_name = 'PUOrder'

  enum Status: ["Chưa thực hiện", "Đang thực hiện", "Hoàn thành" ]

  has_many :pu_order_detail, foreign_key: :RefID
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  establish_connection DB_CONF
  self.table_name = 'Unit'
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :roles, :join_table => :users_roles
end

app/controllers/show_map_controller.rb
class ShowMapController < ApplicationController
  authorize_resource :class => false
  def index
    @list_unit = Unit.all
    @list_map = MapPurchase.all.map(&:map_id).uniq
    @list_map = MapPurchase.where("map_id LIKE '%#{params[:name]}%'").map(&:map_id).uniq if params[:name].present?
    if params[:list_map].nil?
      @list_order = MapPurchase.where( map_id: @list_map.first)
    else
      @list_order = MapPurchase.where( map_id: params[:list_map])
    end
  end

  def delete_map_order
    if params[:list_map].present?
      params[:list_map].each do |id|
        map_purchase = MapPurchase.find_by_id(id)
        if map_purchase.map_item.destroy_all
          map_purchase.destroy
        end
      end
    end
    redirect_to show_map_index_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/export_helper.rb
module ExportHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/map_order_helper.rb
module MapOrderHelper

  def show_unit(unit_id)
    @list_unit.find{|u| u.UnitID == unit_id }.try(:UnitName)
  end

  def volume(volume, quantity)
    volume = volume.nil? ? 0 : volume
    volume*quantity
  end

  def weight(weight, quantity)
    weight = weight.nil? ? 0 : weight
    weight*quantity
  end
end

app/helpers/show_map_helper.rb
module ShowMapHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/show_map/index.html.erb
<section class="content">
  <div class="wrapper">
<div class="pull-right" style="margin-bottom: 20px;">
  <%= form_tag show_map_index_path,:method => :get do %>
      <div class="col-md-12" style="margin-top: 20px;">
         <p class="float_left" style="color: red;"> <b>Nhập Tên Tìm Kiếm: &nbsp</b></p>
         <div class="float_left">
        <%= text_field_tag("name","" , class: "form-control ")%>
        </div>
      <%= submit_tag "Search", class: "btn btn-primary float_left" %>
     </div>
    <% end %>
</div>
  <br>  

  <%= form_tag show_map_index_path, :name => "switch_car",:method => :get do %>
    <div class="field col-md-4">
        <label>Chọn Tên Để Show</label>
        <%= select_tag "list_map", options_for_select(@list_map, selected: params[:list_map]), { class: "form-control", :onchange => "this.form.submit()"}%>
    </div>

    <% end %>
   <br>

<div style="margin-top: 20px;">
<%= form_tag creates_map_order_index_path do %>

  <div class="panel panel-primary">
    <div class="panel-heading">Chi tiết gom container</div>
      <div class="panel-body" style="max-height: 500px;overflow-y: scroll;">
        <div class="row-main panel-body">
      <% @list_order.each do |detail_pus|%>
      <div class="panel-heading">
        <h2 class="panel-title">
          <b style="font-size:16px;">Đơn hàng: <%= detail_pus.purchase_order[0].try(:RefNo)%></b>
        </h2>
      </div>
      <p>Chi tiết đơn hàng</p>
        <% detail_pus.map_item.each do |detail_pu|%>
          <div class="panel panel-default login-form">
              <div class="panel-heading">
                <h3 class="panel-title">
                  <b style="font-size:16px;">Mã hàng: <%= detail_pu.inventory_item[0].InventoryItemCode%></b>
                  <%= hidden_field_tag("Pu[][Item][][InventoryItemID]", detail_pu.pu_order_detail[0].InventoryItemID)%>
                </h3>
              </div>
              <div class="panel-body">
                <div class="">
            <table style="width:90%;font-size:15px;">
              <tr class="states">
                <td colspan="3" style="float: left;">
                <div style="width: 950px" class="alert alert-success">Nhập vào số lượng để tính toán thể tích khối lượng
                  <span style="float: left;">Số lượng:</span><span class="col-md-3"> <%= number_field_tag 'Pu[][Item][][quantity]', detail_pu.quantity, class: "form-control quantity margin_top"  %></span></div>
                </td>
              </tr>
              <tr>
                <%= hidden_field_tag("volume_detail", detail_pu.pu_order_detail[0].item.try(:volume), {class: "volume_detail"})%>
                <td colspan="">
                  <div style="height: 50px" class="alert alert-warning">
                  <div style="width: 290%">
                    <span class="float_left">Thể tích:</span> <div class="col-md-2 volume"><b><%= volume(detail_pu.pu_order_detail[0].item.try(:volume), detail_pu.quantity)%></b> </div>
                  </div>
                  <div>
                    <span class="float_left">Khối lượng: </span><div class="col-md-2 weight"> <b> <%= weight(detail_pu.pu_order_detail[0].item.try(:weight), detail_pu.quantity)%></b></div>
                  </div>
                  </div>
                </td>
                  <%= hidden_field_tag("weight_detail", detail_pu.pu_order_detail[0].item.try(:weight), {class: "weight_detail"})%>
              </tr>
              <tr>
                <td>
                <div style="width: 280%">
                  <span style="float: left;"> Đơn vị tính:</span><span class="col-md-2"> <%= show_unit(detail_pu.pu_order_detail[0].UnitID) %></span>
                  </div>
                  <span class="float_left">Số lượng nhận:</span><span class="col-md-2"> <%= detail_pu.pu_order_detail[0].QuantityReceipt%></span>
                </td>
              </tr>
            </table>
          </div>
              </div>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
</div>
<div class="col-md-12" style="margin-top: 20px;">
  <div style="float: right; width: 25%; height: 100px" class="alert alert-success">
    <div style="text-align: center;"><b> Tổng thể tích(m<sup>3</sup>) </b><br><div style="text-align: center; font-size: 17px" class="the_tich"></div></div>
    <div class="" style="text-align: center;" > <b> Tổng khối lượng(kg) </b> <br><div style="text-align: center; font-size: 17px"  class="khoi_luong"></div></div>
  </div>
  <div style="float: right; width: 30%; height: 80px" class="alert alert-success">
    <div><b class="float_left"> Thể tích của container: </b><div style="text-align: center; font-size: 17px" class="thetich_container">65 m<sup>3</sup></div></div>
    <div  > <b class="float_left"> Khối lượng của container: </b> <div style="" class=""></div><div style=" font-size: 17px; text-align: center;" class="khoiluong_container">25000 kg</div></div>
  </div>
</div>
  <center style="margin-top: 10px; margin-bottom: 15px;">
  <%= link_to "Export", export_index_path(format: :xlsx, params: {list_map: params[:list_map] }), class: "btn btn-primary", onclick: "location"%>
  <%= link_to "Delete", delete_map_order_show_map_index_path(params: {list_map: @list_order.map(&:id) }), class: "btn btn-primary",  data: { confirm: "Are you sure?" }%>
  </center>
</section>