config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  resources :export do
    collection do
      get :export_file
    end
  end

  resources :users_manage

  devise_for :users, :controllers => {registrations: 'registrations'}

  resources :show_map do
    collection do
      get :delete_map_order
    end
  end
    

  resources :items do
    collection do
      get :insert
      get :suppliers
      get :input
      get :add_information
    end
  end

 resources :map_order do
  collection do
    post :creates
  end
 end

  resources :inventory_items
  resources :purchase_orders do
    collection do 
      get :get_data
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    user ||= User.new

    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :moderator
      can :manage, User, user_id: user.id
      can :create, User
      can :manage, :map_order
      can :manage, :show_map
      can :manage, :item
      can :manage, :inventory_item
      can :manage, :purchase_order
      # can :read, :all
    else
       # Guest user aka. anonymous
      # can :read, :all
    end
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/account_object.rb
class AccountObject < ActiveRecord::Base
  establish_connection DB_CONF
  self.table_name = 'AccountObject'
  has_many :item, foreign_key: :supplier_id
  has_one :account_object, primary_key: :AccountObjectID
end

app/models/container_type.rb
class ContainerType < ActiveRecord::Base
  acts_as_paranoid
end

app/models/high_score.rb
class HighScore < ActiveRecord::Base
end

app/models/inventory_item.rb
class InventoryItem < ActiveRecord::Base
  establish_connection DB_CONF
  self.table_name = 'InventoryItem'
  has_one :unit, foreign_key: :UnitID, primary_key: :UnitID
  has_many :item, foreign_key: :item_id, primary_key: :InventoryItemID
end

app/models/item.rb
class Item < ActiveRecord::Base
  acts_as_paranoid
  has_one :account_object , foreign_key: :AccountObjectID, primary_key: :supplier_id
end

app/models/map_item.rb
class MapItem < ActiveRecord::Base
  self.table_name = 'map_item'
  has_many :pu_order_detail ,foreign_key: :InventoryItemID, primary_key: :ItemID
  has_many :inventory_item, foreign_key: :InventoryItemID, primary_key: :ItemID
end

app/models/map_purchase.rb
class MapPurchase < ActiveRecord::Base
  has_many :purchase_order, foreign_key: :RefID, primary_key: :RefID
  has_many :map_item, foreign_key: :map_purchase_id

  validates_presence_of :map_id
end

app/models/pu_order_detail.rb
class PuOrderDetail < ActiveRecord::Base
  establish_connection DB_CONF
  self.table_name = 'PuOrderDetail'

  belongs_to :purchase_order, foreign_key: :RefID
  has_one :item , foreign_key: :item_id, primary_key: :InventoryItemID
  has_one :inventory_item,  foreign_key: :InventoryItemID, primary_key: :InventoryItemID
end

app/models/purchase_order.rb
class PurchaseOrder < ActiveRecord::Base
  establish_connection DB_CONF
  self.table_name = 'PUOrder'

  enum Status: ["Chưa thực hiện", "Đang thực hiện", "Hoàn thành" ]

  has_many :pu_order_detail, foreign_key: :RefID
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  establish_connection DB_CONF
  self.table_name = 'Unit'
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :roles, :join_table => :users_roles
end

app/controllers/users_manage_controller.rb
class UsersManageController < ApplicationController
  authorize_resource :class => false
  before_action :get_user, only: [:edit, :update, :destroy]
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    user =  User.create(user_params)
    user.add_role "moderator" if user.present?
    redirect_to users_manage_index_path
  end

  def update
    if params[:user][:password].blank? || params[:user][:password].nil?
      user = @user.update(user_update)
    else
      user = @user.update(user_params)
    end
    if user
      flash[:notice] = "Cập nhật thành công!"
    else
      flash[:alert] =  "Cập nhật không thành công"
    end
    redirect_to users_manage_index_path
  end

  def edit
  end

  def destroy
    if @user.destroy
      flash[:notice] = " Xóa thành công!"
    else
      flash[:alert] =  " Xóa không thành công"
    end
    redirect_to users_manage_index_path
  end

  private

  def get_user
    @user = User.find_by_id(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :salt, :encrypted_password)
  end

  def user_update
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/export_helper.rb
module ExportHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/map_order_helper.rb
module MapOrderHelper

  def show_unit(unit_id)
    @list_unit.find{|u| u.UnitID == unit_id }.try(:UnitName)
  end

  def volume(volume, quantity)
    volume = volume.nil? ? 0 : volume
    volume*quantity
  end

  def weight(weight, quantity)
    weight = weight.nil? ? 0 : weight
    weight*quantity
  end
end

app/helpers/show_map_helper.rb
module ShowMapHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users_manage/edit.html.erb
<div class= "col-md-4 col-md-offset-3">
  <h2 class="form-signin-heading col-md-offset-4 ">Edit user</h2>

  <%= form_for(@user, url: users_manage_path(@user)) do |f| %>


    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name, autofocus: true, class: "form-control" %>
    </div>

    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true, class: "form-control" %>
    </div>

    <div class="field">
      <%= f.label :password %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
    </div>
    <br>
    <div class="actions">
      <%= f.submit "Update" ,  class:"btn btn-lg btn-primary btn-block" %>
    </div>
  <% end %>
</div>

app/views/users_manage/index.html.erb
<h2>Danh sách user </h2>
<div class="pull-right"> <%=link_to "Create", new_users_manage_path(), class:"btn btn-primary " %></div>
<table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Role</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user|%>
      <tr>
        <td><%= user.name%></td>
        <td><%= user.email%></td>
        <td><%= user.roles.first.try(:name)%></td>
        <td>
        <%  unless user.has_role? :admin %>
          <%= link_to "Edit", edit_users_manage_path(user) %> &nbsp  | &nbsp <%= link_to "Xóa", users_manage_path(user), data: { confirm: "Are you sure?" }, method: :delete %>
        <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/users_manage/new.html.erb
<div class= "col-md-4 col-md-offset-3">
  <h2 class="form-signin-heading col-md-offset-4 ">Create user</h2>

  <%= form_for(@user, url: users_manage_index_path(@user)) do |f| %>


    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name, autofocus: true, class: "form-control" %>
    </div>

    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true, class: "form-control" %>
    </div>

    <div class="field">
      <%= f.label :password %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
    </div>
    <br>
    <div class="actions">
      <%= f.submit "Create" ,  class:"btn btn-lg btn-primary btn-block" %>
    </div>
  <% end %>
</div>