config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  resources :export do
    collection do
      get :export_file
    end
  end

  resources :users_manage

  devise_for :users, :controllers => {registrations: 'registrations'}

  resources :show_map do
    collection do
      get :delete_map_order
    end
  end
    

  resources :items do
    collection do
      get :insert
      get :suppliers
      get :input
      get :add_information
    end
  end

 resources :map_order do
  collection do
    post :creates
  end
 end

  resources :inventory_items
  resources :purchase_orders do
    collection do 
      get :get_data
    end
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  acts_as_paranoid
  has_one :account_object , foreign_key: :AccountObjectID, primary_key: :supplier_id
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  authorize_resource :class => false
  def index
    @items = InventoryItem.all
  end

  def show
    @supplier = AccountObject.where(AccountObjectID: params[:id])
    @items = InventoryItem.all
    @selected_items = @supplier[0].item
    # binding.pry
    gon.selected_items = @selected_items
  end

  def insert
    list_items = InventoryItem.where(InventoryItemID: params[:list_items]) #lisst truyen len
    list_supplier= Item.where(supplier_id: params[:supplier_id]) #list mat hang theo nha cung cap da co
    if params[:list_items].blank?
      list_supplier.destroy_all
    else
      if list_supplier.blank?
        list_items.each do |item|
          params_create = {item_id: item.InventoryItemID,
                           item_code: item.InventoryItemCode,
                           supplier_id: params[:supplier_id]}
          Item.create(params_create)
        end
      else
        temp = list_supplier.where(item_id: params[:list_items]) # mat hang da co theo nha cung cap voi item truyen len 
        list_item_id = temp.map(&:item_id) #tao mang item_id cua item da co
        list_temp = params[:list_items] - list_item_id if params[:list_items].present?#truyen len ma chua co
          if list_temp.present?
            list_items = InventoryItem.where(InventoryItemID: list_temp)
            list_items.each do |item|
              params_create = {item_id: item.InventoryItemID,
                               item_code: item.InventoryItemCode,
                               supplier_id: params[:supplier_id]}
              item_search = Item.find_by(item_id: item.InventoryItemID, supplier_id: nil)
              if item_search.present?
                # binding.pry
                item_search.update(supplier_id: params[:supplier_id] )
              else
                Item.create(params_create)
              end
            end
          end
        list_item_not_select = Item.where(supplier_id: params[:supplier_id]).map(&:item_id)
        # temp = Item.where(supplier_id: params[:supplier_id]).where(item_id: params[:list_items]).map(&:item_id) # mat hang da co theo nha cung cap voi item truyen len 
        # list_item_id = temp.map(&:item_id)
        list_temp_not_params = list_item_not_select - params[:list_items] if params[:list_items].present?
        if list_temp_not_params.present?
          Item.where(item_id: list_temp_not_params).where(supplier_id: params[:supplier_id]).destroy_all
        end
      end
    end
    redirect_to item_path(params[:supplier_id])
  end

  def suppliers
    @suppliers = AccountObject.where(isVendor: 1)
  end

  def input
    @items = PuOrderDetail.all.includes(:inventory_item,:item).group_by(&:InventoryItemID)
    @list_unit = Unit.all
    items_suppliers = Item.all 
    gon.items_suppliers = items_suppliers
    gon.account_object = AccountObject.where(isVendor: 1)
  end

  def add_information
    #binding.pry
    supplier_list = params[:supplier_list]
    if Item.where(item_id: params[:selected_item_id]).blank?
        params_create = {item_id: params[:selected_item_id],
                         weight: params[:weight],
                         volume: params[:volume]}
        Item.create(params_create)
    else
      if supplier_list.blank?
        Item.find_by(item_id: params[:selected_item_id]).update(weight: params[:weight],volume: params[:volume])
      else
        supplier_list.each do |supplier|
          Item.find_by(item_id: params[:selected_item_id], supplier_id: supplier[:supplier_id]).update(weight: params[:weight],volume: params[:volume],supplier_item_code: supplier[:itemid])
        end
      end
    end
    redirect_to input_items_path
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<section class="content">
  <div class="wrapper">
<h3 align="center">HÀNG HÓA</h3>
<table id="item_table" class="display responsive nowrap" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Mã mặt hàng</th>
      <th>Tên mặt hàng</th>
      <th>Đơn vị tính</th>
      <th>Số lượng tồn</th>
      <th>Thể tích</th>
      <th>Khối lượng</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @items.each do |item|%>
      <tr>
          <td><%= item.InventoryItemCode%></td>
          <td><%= item.InventoryItemName%></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td><%= button_to "Chi tiết", purchase_order_path(item.InventoryItemID), method: :get%></td>
      </tr>
      <%end%>
  </tbody>
</table>
</div>
</section>

app/views/items/input.html.erb
<section class="content">
  <div class="wrapper">
    <div class="page-header">
      <h3 align="center">NHẬP THÔNG TIN HÀNG HÓA</h3>
    </div>
    <div class="select_container">
      <div class="items" style="width: 65%">
      <table id="example" class="display responsive nowrap" cellspacing="0" width="100%">
      <thead>
        <tr>
          <th></th>
          <th>Mã mặt hàng</th>
          <th>Đơn vị tính</th>
          <th>Khối lượng</th>
          <th>Thể tích</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item|%>
          <tr>
            <td>
              <div class="radio">
                <label><input type="radio" name="optradio"></label>
              </div>
            </td>
            <input type="hidden" value="<%=item[1][0].inventory_item.InventoryItemID%>"></input>
            <td><%= item[1][0].inventory_item.InventoryItemCode%></td>
            <td class="item_name"><%= show_unit(item[1][0].UnitID)%></td>
            <td class="item_weight"><%= item[1][0].item.try(:weight)%></td>
            <td class="item_volume"><%= item[1][0].item.try(:volume)%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
      <div class="items" style="width: 30%">
        <%= form_tag(add_information_items_path, method: :get) do %>
            <div class="panel panel-primary">
              <div class="panel-heading"><center>Thông tin mặt hàng</center></div>
              <div class="panel-body">
                <table class="table">
                  <thead>
                    <tr>
                      <th colspan="2"><span class="break">Tên Mặt Hàng</span></th>
                    </tr>
                  </thead>
                  <%= hidden_field_tag 'selected_item_id' %>
                  <tr>
                    <td style="width: 43%">Khối lượng (kg):</td>
                    <td><%= text_field_tag 'weight', nil, class: 'form-control', disabled: true%></td>
                  </tr>
                  <tr>
                    <td>Thể tích (m<sup>3</sup>):</td>
                    <td><%= text_field_tag 'volume', nil, class: 'form-control', disabled: true%></td>
                  </tr>
                </table>
              </div>
              <div class="panel-body-selected" style="height: 345px">
                <center><h3>Các nhà cung cấp</h3></center>
                <table class="table table-striped">
                  <thead>
                    <tr>
                      <th class="col-md-7">Nhà cung cấp</th>
                      <th class="col-md-5">Mã mặt hàng (NCC)</th>
                    </tr>
                  </thead>
                  <tbody id="input_item_code">
                  </tbody>
                </table>
              </div>
            </div>
            <%= submit_tag( "Lưu", class: "btn btn-primary btn-lg", style:"width: 100%;", id: "chon" ) %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/items/show.html.erb
<section class="content">
  <div class="wrapper">
    <div class="page-header">
      <h3 align="center">THÔNG TIN NHÀ CUNG CẤP</h3>
    </div>
    <div class="panel panel-default login-form">
          <div class="panel-heading">
            <h3 class="panel-title text-center">
              <i class="glyphicon glyphicon-phone-alt"><b style="font-size:18px;"> Nhà cung cấp: <%=@supplier[0].AccountObjectName %></b></i>
            </h3>
          </div>
          <div class="main panel-body">
            <div class="main-show">
                <table style="width:90%;font-size:18px;">
                  <tr>
                    <td><b>Mã:</b> <%=@supplier[0].AccountObjectCode %></td>
                    <td colspan="2"><b>Mã số thuế:</b> <%=@supplier[0].CompanyTaxCode %></td>
                  </tr>
                  <tr>
                    <td colspan="3"><b>Địa chỉ:</b> <%=@supplier[0].Address %></td>
                  </tr>
                  <tr>
                    <td><b>Số cố định:</b> <%=@supplier[0].Tel %></td>
                    <td><b>Số di động:</b> <%=@supplier[0].Mobile %></td>
                    <td><b>Fax:</b> <%=@supplier[0].Fax %></td>
                  </tr>
                  <tr>
                    <td><b>Email:</b> <%=@supplier[0].EmailAddress %></td>
                    <td colspan="2"><b>Website:</b> <%=@supplier[0].Website %></td>
                  </tr>
                  <tr>
                    <td><b>TK ngân hàng:</b> <%=@supplier[0].BankAccount %></td>
                    <td colspan="2"><b>Tên ngân hàng:</b> <%=@supplier[0].BankName %></td>
                  </tr>
                </table>
                
              </div>
          </div>
    </div>
    <div class="page-header">
      <h3 align="center">CHỌN MẶT HÀNG CHO NHÀ CUNG CẤP</h3>
    </div>
    <div class="select_container">
      <div class="items" style="width: 65%">
        <%= form_tag(insert_items_path, method: :get) do %>
          <%= hidden_field_tag 'supplier_id',  @supplier[0].AccountObjectID %>
          <%= select_tag 'list_items[]', options_for_select(@items.collect{ |u| [u.InventoryItemCode, u.InventoryItemID] }), multiple: true , id: :items%>
      </div>
      <div class="items" style="width: 30%">
          <div class="panel panel-primary">
            <div class="panel-heading"><center>Mặt hàng đã chọn</center></div>
            <div class="panel-body-selected" id="test">
            </div>
          </div>
          <%= submit_tag( "Chọn", class: "btn btn-primary btn-lg", style:"width: 100%;margin-top:-14px;", id: "chon" ) %>
        <% end %>
      </div>
    </div>
    <center style="margin-top: 10px; margin-bottom: 15px;"><%= link_to "Quay lại", suppliers_items_path, class: "btn btn-primary", onclick: "location"%></center>
  </div>
</section>

app/views/items/suppliers.html.erb
<section class="content">
  <div class="wrapper">
    <div class="page-header">
      <h3 align="center">NHÀ CUNG CẤP</h3>
    </div>
    <table id="example" class="display responsive nowrap" cellspacing="0" width="100%">
      <thead>
        <tr>
          <th>Mã NCC</th>
          <th>Tên NCC</th>
          <th>Địa chỉ</th>
          <th>Số điện thoại</th>
          <th>Email</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @suppliers.each do |supplier|%>
          <tr>
            <td><%= supplier.AccountObjectCode%></td>
            <td><span class="text_trunc"><%= supplier.AccountObjectName%></span></td>
            <td><span class="text_trunc"><%= supplier.Address%></span></td>
            <td><%= supplier.Tel%></td>
            <td><%= supplier.EmailAddress%></td>
            <td><%= button_to "Chi tiết", item_path(supplier.AccountObjectID), method: :get%></td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</section>