config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  resources :export do
    collection do
      get :export_file
    end
  end

  resources :users_manage

  devise_for :users, :controllers => {registrations: 'registrations'}

  resources :show_map do
    collection do
      get :delete_map_order
    end
  end
    

  resources :items do
    collection do
      get :insert
      get :suppliers
      get :input
      get :add_information
    end
  end

 resources :map_order do
  collection do
    post :creates
  end
 end

  resources :inventory_items
  resources :purchase_orders do
    collection do 
      get :get_data
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    user ||= User.new

    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :moderator
      can :manage, User, user_id: user.id
      can :create, User
      can :manage, :map_order
      can :manage, :show_map
      can :manage, :item
      can :manage, :inventory_item
      can :manage, :purchase_order
      # can :read, :all
    else
       # Guest user aka. anonymous
      # can :read, :all
    end
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/account_object.rb
class AccountObject < ActiveRecord::Base
  establish_connection DB_CONF
  self.table_name = 'AccountObject'
  has_many :item, foreign_key: :supplier_id
  has_one :account_object, primary_key: :AccountObjectID
end

app/models/container_type.rb
class ContainerType < ActiveRecord::Base
  acts_as_paranoid
end

app/models/high_score.rb
class HighScore < ActiveRecord::Base
end

app/models/inventory_item.rb
class InventoryItem < ActiveRecord::Base
  establish_connection DB_CONF
  self.table_name = 'InventoryItem'
  has_one :unit, foreign_key: :UnitID, primary_key: :UnitID
  has_many :item, foreign_key: :item_id, primary_key: :InventoryItemID
end

app/models/item.rb
class Item < ActiveRecord::Base
  acts_as_paranoid
  has_one :account_object , foreign_key: :AccountObjectID, primary_key: :supplier_id
end

app/models/map_item.rb
class MapItem < ActiveRecord::Base
  self.table_name = 'map_item'
  has_many :pu_order_detail ,foreign_key: :InventoryItemID, primary_key: :ItemID
  has_many :inventory_item, foreign_key: :InventoryItemID, primary_key: :ItemID
end

app/models/map_purchase.rb
class MapPurchase < ActiveRecord::Base
  has_many :purchase_order, foreign_key: :RefID, primary_key: :RefID
  has_many :map_item, foreign_key: :map_purchase_id

  validates_presence_of :map_id
end

app/models/pu_order_detail.rb
class PuOrderDetail < ActiveRecord::Base
  establish_connection DB_CONF
  self.table_name = 'PuOrderDetail'

  belongs_to :purchase_order, foreign_key: :RefID
  has_one :item , foreign_key: :item_id, primary_key: :InventoryItemID
  has_one :inventory_item,  foreign_key: :InventoryItemID, primary_key: :InventoryItemID
end

app/models/purchase_order.rb
class PurchaseOrder < ActiveRecord::Base
  establish_connection DB_CONF
  self.table_name = 'PUOrder'

  enum Status: ["Chưa thực hiện", "Đang thực hiện", "Hoàn thành" ]

  has_many :pu_order_detail, foreign_key: :RefID
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  establish_connection DB_CONF
  self.table_name = 'Unit'
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :roles, :join_table => :users_roles
end

app/helpers/export_helper.rb
module ExportHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/map_order_helper.rb
module MapOrderHelper

  def show_unit(unit_id)
    @list_unit.find{|u| u.UnitID == unit_id }.try(:UnitName)
  end

  def volume(volume, quantity)
    volume = volume.nil? ? 0 : volume
    volume*quantity
  end

  def weight(weight, quantity)
    weight = weight.nil? ? 0 : weight
    weight*quantity
  end
end

app/helpers/show_map_helper.rb
module ShowMapHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<script>
      String.prototype.trunc = String.prototype.trunc ||
      function(n){
          return (this.length > n) ? this.substr(0,n-1)+'...' : this;
      };

      $(document).ready(function() {
          $(".text_trunc").each(function(){
            var text_trunc =$(this).text();
            $(this).attr('title',text_trunc);
            text_trunc = text_trunc.trunc(25);
            $(this).text(text_trunc);
          });
          

          $('#example').DataTable({
            responsive: {
                  details: {
                      renderer: function ( api, rowIdx, columns ) {
                          var data = $.map( columns, function ( col, i ) {
                              return col.hidden ?
                                  '<tr data-dt-row="'+col.rowIndex+'" data-dt-column="'+col.columnIndex+'">'+
                                      '<td>'+col.title+':'+'</td> '+
                                      '<td>'+col.data+'</td>'+
                                  '</tr>' :
                                  '';
                          } ).join('');
       
                          return data ?
                              $('<table/>').append( data ) :
                              false;
                      }
                  }
            }
        });
        $("#items").selectr({
            title: 'Danh sách mặt hàng',
            placeholder: 'Tên mặt hàng',
        });
        $("#purchase_orders").selectr({
            title: 'Danh sách đơn hàng',
            placeholder: 'Mã đơn hàng',
        });
        
        $('.add-remove').click(function() {
          var x = $(this).siblings(".option-name").text();
            if($(this).parent('.list-group-item').hasClass("selected")){
              $("#items").find("option").each(function(){
                if(x == $(this).text()){
                  $("#"+$(this).val()).remove();
                }
              });
            }
            else{
              $("#items").find("option").each(function(){
                if(x == $(this).text()){
                  $('.panel-body-selected').append("<p id="+$(this).val()+">- "+x+"</p>");
                  return false;
                }
              });
            }
        });

        $('.option-name').click(function(){
          $('.panel-body-selected').find('p').remove();
          var x = $(this).text();
          if((!$(this).parent('.list-group-item').hasClass("selected")) || ($(this).parent('.list-group-item').siblings().hasClass("selected"))){
              $("#items").find("option").each(function(){
                if(x == $(this).text()){
                  $('.panel-body-selected').append("<p id="+$(this).val()+">- "+x+"</p>");
                  return false;
                }
              });
          }
        });
        $('.reset').click(function(){
          $('.panel-body-selected').find('p').remove();
        });


      });
      
</script>
<footer class= "app-footer wrapper">
   <span> &nbsp; version 1.0 </span>
   <span> © 2016 Copyright KietChien</span>
</footer>

app/views/layouts/_header.html.erb
<div style="height: 100px" class="controls">
<p class="navbar-text pull-right">
</p>
<div style="margin-left: 50px">
  <img src="<%= asset_path "bn-53857.png"%>">
</div>
</div>

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-default.navbar-fixed-top.navbar-top
  .container-fluid
    .navbar-header
      button.navbar-expand-toggle[type="button"]
        i.fa.fa-bars.icon
      ol.breadcrumb.navbar-breadcrumb
        li
          | Something
        li.active
          | Here
      button.navbar-right-expand-toggle.pull-right.visible-xs[type="button"]
        i.fa.fa-th.icon
    ul.nav.navbar-nav.navbar-right style= "margin-top: -20px; margin-bottom: -21px;"
      li.dropdown.profile
        a.dropdown-toggle[href="#" data-toggle="dropdown" role="button" aria-expanded="false"]
          img src=asset_path('default-avatar.png')
          =<> current_user.name
          span.caret
        ul.dropdown-menu.animated.fadeInDown
          li
            .profile-info
              h4.username
                = current_user.name
              p
                = current_user.email
              .btn-group.margin-bottom-2x[role="group"]
                = link_to 'Edit profile', edit_user_registration_path, class: "btn btn-default"
                =link_to 'Logout', destroy_user_session_path, :method => :delete, class: "btn btn-default"

app/views/layouts/_sidebar.html.erb
<!-- SIDEBAR MENU -->
<div class="profile-usermenu">
  <ul class="nav">
    <li class="active">
      <a href="/">
      Home </a>
    </li>
    <li>
      <%= link_to "Danh sách đơn hàng ", purchase_orders_path%>
    </li>
    <li>
      <%= link_to "Dữ liệu gom container", show_map_index_path%>
    </li>
    <li>
      <%= link_to "Gom đơn hàng vào container", map_order_index_path%>
    </li>
    <li>
      <%= form_tag(input_items_path, method: :get) do %>
        <%= submit_tag("Nhập khối lượng thể tích cho mặt hàng",class: "btn btn-link sidebar_input")%>
      <% end %>
      
    </li>
    <li>
      <%= link_to "Danh sách nhà cung cấp ", suppliers_items_path%>
    </li>
  </ul>
</div>
<!-- END MENU -->

app/views/layouts/_sidebar.html.slim
.side-menu.sidebar-inverse
  nav.navbar.navbar-default role="navigation"
    .side-menu-container
      .navbar-header
        a.navbar-brand href="#"
          img src=asset_path("bn-53857.png") alt="logo" height="60" width="190"
          .title= current_user.name
        button.navbar-expand-toggle.pull-right.visible-xs type="button"
          i.fa.fa-times.icon
      ul.nav.navbar-nav
        li.panel.panel-default.dropdown
          a data-toggle="collapse" href="#dropdown-sr"
            span.icon.fa.fa-list
            span.title Quản Lý Gomcon
          #dropdown-sr.panel-collapse.collapse
            .panel-body
              ul.nav.navbar-nav
                li
                  a href=purchase_orders_path Danh sách đơn hàng
                li
                  a href=show_map_index_path Dữ liệu gom container
                li
                  a href=map_order_index_path Gom đơn hàng vào container
                li
                  a href=suppliers_items_path Danh sách nhà cung cấp
                li
                  a href=input_items_path Nhập khối lượng thể tích cho mặt hàng
        -if current_user.has_role? :admin
          li.panel.panel-default.dropdown
            a data-toggle="collapse" href="#dropdown-settings"
              span.icon.fa.fa-cogs
              span.title Quản Lý Tài Khoản
            #dropdown-settings.panel-collapse.collapse
              .panel-body
                ul.nav.navbar-nav
                  li
                    a href=users_manage_index_path Danh Sách Tài Khoản

app/views/layouts/_sidebar1.tml.erb
<!-- SIDEBAR MENU -->
<div class="profile-usermenu">
  <ul class="nav">
    <li class="active">
      <a href="/">
      Home </a>
    </li>
    <li>
      <%= link_to "Danh sách đơn hàng ", purchase_orders_path%>
    </li>
    <li>
      <%= link_to "Dữ liệu gom container", show_map_index_path%>
    </li>
    <li>
      <%= link_to "Gom đơn hàng vào container", map_order_index_path%>
    </li>
    <li>
      <%= form_tag(input_items_path, method: :get) do %>
        <%= submit_tag("Nhập khối lượng thể tích cho mặt hàng",class: "btn btn-link sidebar_input")%>
      <% end %>
      
    </li>
    <li>
      <%= link_to "Danh sách nhà cung cấp ", suppliers_items_path%>
    </li>
  </ul>
</div>
<!-- END MENU -->

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content="IE=edge" http-equiv="X-UA-Compatible" /
    meta content="width=device-width, initial-scale=1" name="viewport" /
    link rel="shortcut icon" href="/favicon.ico"
    title GomCon
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    link href="http://fonts.googleapis.com/css?family=Roboto+Condensed:300,400" rel="stylesheet" type="text/css" /
    link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,900" rel="stylesheet" type="text/css" /
  body.flat-green
    .app-container.expanded
      .row.content-container
        = render 'layouts/navbar'
        = render 'layouts/sidebar'
        .container-fluid
          .side-body
            = yield
        = render 'layouts/footer'

app/views/layouts/layout_for_devise.html.erb
<!DOCTYPE html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Home | Corlate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= include_gon %>
</head>
<body>
  <div id="wrapper">
    <div class="header">
      <%= render 'layouts/header' %>
    </div>
    <div class="body_content" style="min-height: 457px;">
        <div class="col-md-10">
          <%= yield %>
        </div>
    </div>
    <div class="footer">
      <%= render 'layouts/footer' %>
    </div>
  </div>
</body>
</html>